# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.TextField()),
                ('pole_id', models.TextField()),
                ('light_type', models.TextField()),
                ('pole_mfg', models.TextField()),
                ('fixture_mfg', models.TextField()),
                ('tech', models.TextField()),
                ('nema', models.TextField()),
                ('fiber', models.TextField()),
                ('wireless', models.TextField()),
                ('energy_use', models.TextField()),
                ('lumens', models.TextField()),
                ('past_energy_use', models.TextField()),
                ('misc', models.TextField()),
            ],
        ),
    ]
