# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pole',
            name='lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pole',
            name='fiber',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pole',
            name='fixture_mfg',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pole',
            name='light_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pole',
            name='lumens',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pole',
            name='nema',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pole',
            name='owner',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pole',
            name='pole_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pole',
            name='pole_mfg',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pole',
            name='tech',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pole',
            name='wireless',
            field=models.CharField(max_length=200),
        ),
    ]
